---
# Home Assistant Glow
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# © Klaas Schoute
#
substitutions:
  device_name: home-assistant-glow
  friendly_name: Home Assistant Glow
  project_version: "4.2.3"
  device_description: "Measure your energy consumption with the pulse LED on your smart meter - ESP32 Generic"

  # Define the GPIO pins
  pulse_pin: GPIO14
  status_led: GPIO5
  led_pin_red: GPIO2
  led_pin_green: GPIO4

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "sdholden28.home-assistant-glow"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://sdholden28/home-assistant-glow/home-assistant-glow/esp32.yaml@main

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  remote_package:
    url: https://github.com/sdholden28/home-assistant-glow/
    ref: "4.2.3"
    files:
      - components/basis.yaml
      - components/updates.yaml
      - components/status_led.yaml
      - components/pulse_meter.yaml

# Enable logging
logger:

# Local Web Server running on port 80
web_server:
  id: esphome_web_server
  version: 3
